[package]
name = "hp_mfp_m281cdw"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# I only trust this exact version. You should not update it.
ftp = "=3.0.1"